### PR TITLE
Fixed Glowing Color

### PR DESCRIPTION
**Pull request by Etheradon**
This should finally fix the glowing color bug for 1.17.

### CODE REVIEW

**Comment by Etheradon** [comment]
Also added an option to change the glowing color

**Comment by wagyourtail** [comment]
you do a bit more than what the title says...

**Comment by wagyourtail** [comment]
~~hey I was reviewing your refactoring~~

**Comment by Etheradon** [comment]
Oh, I didn't know that I would submit the main branch, since Fixed Color was in a separate one. I should have fixed it now.

**Pull request merged**
